// keep some config data in here

export const FEATURE_GROUPS: Map<string, string> = new Map<string, string>([
  ["object--banner", "Banner"], 
  ["object--bench", "Bench"], 
  ["object--bike-rack", "Bike rack"], 
  ["object--catch-basin", "Catch basin"], 
  ["object--cctv-camera", "CCTV camera"], 
  ["construction--flat--crosswalk-plain", "Crosswalk - plain"], 
  ["construction--flat--driveway", "DriveWay"], 
  ["object--fire-hydrant", "Fire hydrant"], 
  ["object--junction-box", "Junction box"], 
  ["marking--discrete--arrow--left", "Lane marking (left)"], 
  ["marking--discrete--arrow--right", "Lane marking (right)"], 
  ["marking--discrete--arrow--split-left-or-straight", "Lane marking (straight - left)"], 
  ["marking--discrete--arrow--split-right-or-straight", "Lane marking (straight - right)"], 
  ["marking--discrete--arrow--straight", "Lane marking (straight)"], 
  ["marking--discrete--crosswalk-zebra", "Lane marking - crosswalk"], 
  ["marking--discrete--give-way-row", "Lane marking - give way(row)"], 
  ["marking--discrete--give-way-single", "Lane marking - give way(single)"], 
  ["marking--discrete--other-marking", "Lane marking - other"], 
  ["marking--discrete--stop-line", "Lane marking - stop line"], 
  ["marking--discrete--symbol--bicycle", "Lane marking - symbol bicycle"], 
  ["marking--discrete--text", "Lane marking - text"], 
  ["object--mailbox", "Mailbox"], 
  ["object--manhole", "Manhole"], 
  ["object--parking-meter", "Parking meter"], 
  ["object--phone-booth", "Phone booth"], 
  ["object--support--pole", "Pole"], 
  ["object--sign--advertisement", "Signage - advertisement"], 
  ["object--sign--information", "Signage - information"], 
  ["object--sign--store", "Signage - store"], 
  ["object--street-light", "Street - light"], 
  ["construction--barrier--temporary", "Temporary barrier"], 
  ["object--traffic-cone", "Traffic cone"], 
  ["object--traffic-light--cyclists", "Traffic light - cyclists"], 
  ["object--traffic-light--other", "Traffic light - other"], 
  ["object--traffic-light--general-horizontal", "Traffic light - horizontal"], 
  ["object--traffic-light--general-single", "Traffic light - single"], 
  ["object--traffic-light--general-upright", "Traffic light - upright"], 
  ["object--support--traffic-sign-frame", "Traffic sign - frame"], 
  ["object--trash-can", "Trash can"], 
  ["object--support--utility-pole", "Utility pole"], 
  ["object--water-valve", "Water valve"]
]);

